version: "3"
dotenv: [".env"]
includes:
  web:
    taskfile: ./apps/web

tasks:
  py:init: POETRY_VIRTUALENVS_IN_PROJECT=true poetry install --no-cache --no-interaction --all-extras
  py:run: poetry run python3 {{.CLI_ARGS}}

  stripe:
    cmds:
      - stripe listen --print-secret | tr -d '\r\n' | (echo -n 'STRIPE_WEBHOOK_SECRET="'; cat; echo '"') > .env.stripe
      - stripe listen --skip-verify --forward-to http://localhost:8788/webhook/stripe
  bacon: bacon {{.CLI_ARGS}}
  stat: btop -f hyprnote -u 500 --preset 1

  clean-plugins:
    cmds:
      - find plugins -mindepth 1 -maxdepth 1 -type d ! -exec test -f {}/Cargo.toml \; -exec rm -rf {} \;

  diff:
    vars:
      DIFF_FROM: "desktop_v0.0.79"
      DIFF_TO: "desktop_v0.0.80"
      PATHS: "apps/desktop/src-tauri plugins crates"
    cmds:
      - git diff {{.DIFF_FROM}} {{.DIFF_TO}} -- {{.PATHS}} | diff2html -i stdin

  jsonschema:
    cmds:
      - |
          jsonschema validate ./plugins/db/seed/schema.json ./plugins/db/seed/onboarding.json
          jsonschema validate ./plugins/db/seed/schema.json ./plugins/db/seed/dev.json

  i18n:
    cmds:
      - |
          pnpm -F desktop lingui:extract |
          awk -F '│' '($2 ~ /[^ ]/ && $3 ~ /[0-9-]/) {
            gsub(/^ *| *$/, "", $2);
            gsub(/[^0-9-]/, "", $3);
            gsub(/^ *| *$/, "", $4);
            printf "{\"language\":\"%s\",\"total\":%d,\"missing\":%d}\n",
              $2,
              ($3 == "-" ? 0: $3),
              ($4 == "-" ? 0: $4)
          }'

  stt:
    cmds:
      - chmod +x ./apps/desktop/src-tauri/resources/stt-aarch64-apple-darwin
      - chmod +x ./apps/desktop/src-tauri/resources/passthrough-aarch64-apple-darwin

  db:
    env:
      DB: /Users/yujonglee/Library/Application Support/hyprnote/db.sqlite
    cmds:
      - |
          sqlite3 -json "$DB" 'SELECT store FROM main LIMIT 1;' |
          jq -r '.[0].store' |
          jless

  env-sample:
    vars:
      INPUT_ENV: '{{.INPUT_ENV | default ".env"}}'
      OUTPUT_ENV: '{{.OUTPUT_ENV | default ".env.sample"}}'
    cmds:
      - sed -E '/^[A-Z_][A-Z0-9_]*=/s/=.*/=""/' {{.INPUT_ENV}} > {{.OUTPUT_ENV}}

  supabase:
    cmds:
      - pnpm exec supabase {{.CLI_ARGS}}

  supabase-stop:
    cmds:
      - pnpm exec supabase stop
      - task: supabase-tunnel-stop

  supabase-tunnel-start:
    platforms: [darwin]
    cmds:
      - bash scripts/supabase-tunnel-start.sh

  supabase-expose:
    platforms: [darwin]
    cmds:
      - task: supabase-tunnel-stop
      - task: supabase-env
      - task: supabase-tunnel-start

  supabase-no-expose:
    platforms: [darwin]
    cmds:
      - task: supabase-tunnel-stop
      - task: supabase-env

  supabase-tunnel-stop:
    platforms: [darwin]
    cmds:
      - bash scripts/supabase-tunnel-stop.sh

  supabase-env:
    internal: true
    cmds:
      - |
          pnpm exec supabase status --output=env | awk -F= '
            /^ANON_KEY=/ { print "SUPABASE_ANON_KEY=" $2; print "VITE_SUPABASE_ANON_KEY=" $2 }
            /^API_URL=/ { print "SUPABASE_URL=" $2; print "VITE_SUPABASE_URL=" $2 }
            /^DB_URL=/ { print "DATABASE_URL=" $2 }
            /^FUNCTIONS_URL=/ { print "SUPABASE_FUNCTIONS_URL=" $2; print "VITE_SUPABASE_FUNCTIONS_URL=" $2 }
            /^GRAPHQL_URL=/ { print "SUPABASE_GRAPHQL_URL=" $2; print "VITE_SUPABASE_GRAPHQL_URL=" $2 }
            /^INBUCKET_URL=/ { print "SUPABASE_INBUCKET_URL=" $2 }
            /^JWT_SECRET=/ { print "SUPABASE_JWT_SECRET=" $2 }
            /^MAILPIT_URL=/ { print "SUPABASE_MAILPIT_URL=" $2 }
            /^MCP_URL=/ { print "SUPABASE_MCP_URL=" $2 }
            /^PUBLISHABLE_KEY=/ { print "SUPABASE_PUBLISHABLE_KEY=" $2; print "VITE_SUPABASE_PUBLISHABLE_KEY=" $2 }
            /^REST_URL=/ { print "SUPABASE_REST_URL=" $2; print "VITE_SUPABASE_REST_URL=" $2 }
            /^SECRET_KEY=/ { print "SUPABASE_SECRET_KEY=" $2 }
            /^SERVICE_ROLE_KEY=/ { print "SUPABASE_SERVICE_ROLE_KEY=" $2 }
            /^STUDIO_URL=/ { print "SUPABASE_STUDIO_URL=" $2 }
          ' > .env.supabase

  # infisical run --env=dev --projectId=87dad7b5-72a6-4791-9228-b3b86b169db1 --path="/supabase" -- task supabase-start
  supabase-start:
    cmds:
      - curl -o supabase/config.toml https://gist.githubusercontent.com/yujonglee/c0704ebe0818621a64753d663c4fcaff/raw/b82572dfcb6ffa4d20c332a8dd7650e5b82b99c3/supabase-default.toml
      - dasel put -f supabase/config.toml -t int -v 17 'db.major_version'
      - dasel put -f supabase/config.toml -t string -v 'http://localhost:3000' 'auth.site_url'
      - dasel put -f supabase/config.toml -t json -v '["http://localhost:3000/callback/auth"]' 'auth.additional_redirect_urls'
      - '[ -n "$GITHUB_CLIENT_ID" ] && [ -n "$GITHUB_CLIENT_SECRET" ] && dasel put -f supabase/config.toml -t bool -v true ''auth.external.github.enabled'' || true'
      - '[ -n "$GITHUB_CLIENT_ID" ] && [ -n "$GITHUB_CLIENT_SECRET" ] && dasel put -f supabase/config.toml -t string -v ''{{.GITHUB_CLIENT_ID}}'' ''auth.external.github.client_id'' || true'
      - '[ -n "$GITHUB_CLIENT_ID" ] && [ -n "$GITHUB_CLIENT_SECRET" ] && dasel put -f supabase/config.toml -t string -v ''{{.GITHUB_CLIENT_SECRET}}'' ''auth.external.github.secret'' || true'
      - '[ -n "$GITHUB_CLIENT_ID" ] && [ -n "$GITHUB_CLIENT_SECRET" ] && dasel put -f supabase/config.toml -t string -v '''' ''auth.external.github.redirect_uri'' || true'
      - '[ -n "$GOOGLE_CLIENT_ID" ] && [ -n "$GOOGLE_CLIENT_SECRET" ] && dasel put -f supabase/config.toml -t bool -v true ''auth.external.google.enabled'' || true'
      - '[ -n "$GOOGLE_CLIENT_ID" ] && [ -n "$GOOGLE_CLIENT_SECRET" ] && dasel put -f supabase/config.toml -t string -v ''{{.GOOGLE_CLIENT_ID}}'' ''auth.external.google.client_id'' || true'
      - '[ -n "$GOOGLE_CLIENT_ID" ] && [ -n "$GOOGLE_CLIENT_SECRET" ] && dasel put -f supabase/config.toml -t string -v ''{{.GOOGLE_CLIENT_SECRET}}'' ''auth.external.google.secret'' || true'
      - '[ -n "$GOOGLE_CLIENT_ID" ] && [ -n "$GOOGLE_CLIENT_SECRET" ] && dasel put -f supabase/config.toml -t bool -v false ''auth.external.google.skip_nonce_check'' || true'
      - dasel put -f supabase/config.toml -t bool -v true 'auth.hook.custom_access_token.enabled'
      - dasel put -f supabase/config.toml -t string -v 'pg-functions://postgres/public/custom_access_token_hook' 'auth.hook.custom_access_token.uri'
      # - '[ ! -f supabase/signing_keys.json ] && pnpm exec supabase gen signing-key --algorithm ES256 | jq -s ''.'' > supabase/signing_keys.json || true'
      # - dasel put -f supabase/config.toml -t string -v './signing_keys.json' 'auth.signing_keys_path'
      - pnpm exec dprint fmt supabase/config.toml
      - pnpm exec supabase start -x realtime,logflare
      - task: supabase-env
      - pnpm exec supabase migration up --local
